name: Buy a lotto645 weekly
on:
  schedule:
    - cron: '0 22 * * 6'
jobs:
  run-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: seongilp/dhlottery-api@publish
        with:
          id: ${{ secrets.ID }}
          pwd: ${{ secrets.PASSWORD }}
